// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

import './build/index.gen.css'
;

function FrameComponent$default(Props) {
  var children = Props.children;
  return React.createElement(React.Fragment, undefined, children);
}

var $$default = FrameComponent$default;

export {
  $$default ,
  $$default as default,
  
}
/*  Not a pure module */
